### Read all movies with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/movies

### Read all movies sorted by duration

GET {{baseUrl}}/movies/?minimum-duration=3

### Read One : the  identified resource 
GET {{baseUrl}}/movies/2

### Add a film
POST {{baseUrl}}/movies
Content-Type: application/json

{
    "title":"movie5",
    "duration":10,
    "budget":400,
    "link":"https://bonjour.Com"
}


### Delete a movie specified
DELETE {{baseUrl}}/movies/4

### Update the resource property identified 
PATCH {{baseUrl}}/movies/3
Content-Type: application/json

{
    "title":"movie6",
    "duration":"3000"
}